let mekanlar =
  [
    "Evde",
    "Otelde",
    "Mezarlıkta",
    "Otoyolda",
    "Marsta",
    "Bilgisayarın İçinde",
    "Uzay Boşluğunda",
    "Okulda",
    "Fabrikada",
    "Kedinin Beyninin İçinde",
    "Köpek Kulübesinde",
    "Tren İstasyonunda",
    "Havadaki Bir Uçakta",
    "Bakterilerin Dünyasında",
    "Sanal Dünyada",
    "Ejderhaların Yaşadığı Mistik Evrende",
    "İkinci Dünya Savaşında",
    "Dişçide",
    "Hastanede",
    "Traktörün Kasasında",
    "Su Şişesinin İçinde",
    "Paralel Evrende",
    "Güneşte",
    "Hava Limanında",
    "Gemide",
    "Okyanusun Derinliklerinde",
    "Açık Denizde",
    "Issız Adada",
    "Elektrik Süpürgesinin İçinde",
    "Pixel Dünyasında",
    "Şehirde",
    "Küçük Bir Kasabada",
    "Ormanda",
    "Ayda",
    "Uzay Gemisinde",
    "Asitle Dolu Bir Havuzda",
    "Zeminin Lav Olduğu Bir Cehennemde",
    "Karlı Bir Günde",
    "Aşırı Sıcak Bir Tropik Adada",
    "Savaş Gemisinde",
    "Rüyada",
    "Atom Altı Evrende"
  ]